#!/usr/bin/env python3
"""
Generates engine.conf (http context): a pure-nginx (map + PCRE, no Lua/njs)
test "does this query string consist ONLY of marketing params?", plus the
helper variables used by php-context.conf.

The param list (params.list) is `include`d into every per-param lookup map,
so editing the list never requires regenerating the engine.

Usage:  python3 build-engine.py [max_params] [max_query_len] [install_dir] > <file>
        (defaults: 24 params, 2048 bytes, /etc/nginx/marketing-params)
        install.sh calls this for you and keeps your limits in limits.env.
"""
import sys

MAX = int(sys.argv[1]) if len(sys.argv) > 1 else 24
MAX_LEN = int(sys.argv[2]) if len(sys.argv) > 2 else 2048
DIR = (sys.argv[3] if len(sys.argv) > 3 else "/etc/nginx/marketing-params").rstrip("/")
MAX_PATH = 8192

# Each param adds ~1 level of nested variable evaluation; nginx stops at 100
# ("cycle while evaluating variable", which fails safe = stock bypass).
# Each param also registers 4 variables; GridPane's variables_hash_max_size is
# 2048, so keep the default low enough to leave headroom for GridPane itself.
assert 1 <= MAX <= 48, "max_params must be 1..48"
assert 64 <= MAX_LEN <= 8192, "max_query_len must be 64..8192"

HEADER = r'''# #
# Marketing params ignored by the GridPane FastCGI cache - ENGINE (http context)
# GENERATED by build-engine.py (max @MAX@ params, max @MAX_LEN@ bytes) - do not edit.
#
# Param list (edit this): @DIR@/params.list
#
# References only its own variables and nginx core variables (never GridPane's),
# so it cannot break `nginx -t` whatever GridPane does with the vhosts.
# All maps are lazy: nothing runs unless php-context.conf references it, and the
# param chain only runs when GridPane's ONLY skip reason is the query string.
# #

# Declared here so php-context.conf can always reference/set them.
map "" $gp_mkt_fcgi   { default ""; }   # set to 1 by the FastCGI-only site flag file
map "" $gp_mkt_in     { default ""; }
map "" $gp_mkt_unskip { default ""; }
map "" $gp_mkt_sc     { default ""; }
map "" $gp_mkt_sr     { default ""; }

# Raw path / raw query from $request_uri (immutable across internal redirects).
map $request_uri $gp_mkt_path {
    "~^(?<gpmkt_path>[^?]*+)"  $gpmkt_path;
}
# Queries longer than @MAX_LEN@ bytes (or paths longer than @MAX_PATH@) become a
# sentinel that never equals $args -> stock GridPane behaviour (bypass).
map $request_uri $gp_mkt_qs {
    "~^[^?]{0,@MAX_PATH@}+\?(?<gpmkt_qs>.{0,@MAX_LEN@}+)$"  $gpmkt_qs;
    "~\?"                                         "gp_mkt_qs_too_long";
    default                                       "";
}
# Leading '&'s are separator noise.
map $gp_mkt_qs $gp_mkt_q0 {
    "~^&*+(?<gpmkt_r>.*+)$"  $gpmkt_r;
}

# ---- param chain: $gp_mkt_j1 = "" when every param is a marketing param,
#      "x" as soon as one real param is found (and it stops right there).
'''

STEP = r'''# param #@I@
map $@R_PREV@ $gp_mkt_n@I@ {
    "~^(?<gpmkt_n>[^&=]*+)"  $gpmkt_n;
}
map $gp_mkt_n@I@ $gp_mkt_m@I@ {
    default 0;
    include @DIR@/params[.]list;
}
map $@R_PREV@ $gp_mkt_r@I@ {
    "~^[^&]*+&++(?<gpmkt_r>.*+)$"  $gpmkt_r;    # runs of '&' count as one separator
    default                        "";
}
map "$gp_mkt_m@I@|$@R_PREV@" $gp_mkt_j@I@ {
    "~^0\|[^&]"  "x";                 # real (non-marketing) param -> not cacheable
    "~^.\|$"     "";                  # end of query string
    default      $gp_mkt_j@NEXT@;     # marketing param -> next one
}
'''

FOOTER = r'''# More than @MAX@ params left -> treat as a real param (stock bypass).
map $gp_mkt_r@MAX@ $gp_mkt_j@MAX1@ {
    ""       "";
    default  "x";
}

# "1" = the (capped) query string consists only of marketing params.
map $gp_mkt_j1 $gp_mkt_allmkt {
    ""       "1";
    default  "0";
}

# ---- decision, evaluated in the php location (after every server-level skip
# rule and every rewrite). php-context.conf sets
#   $gp_mkt_in = "$gp_mkt_fcgi|$skip_reason|$request_method|$gp_mkt_qs#$args"
# Un-skip only if: the vhost is a GridPane FastCGI-cache vhost (flag set by the
# site's *skip-fcgi-cache-context.conf, which only the FastCGI template includes),
# GridPane's ONLY skip reason is the query string, GET/HEAD, $args are still the
# original query ('#' never occurs in $args), and every param is on the list.
map $gp_mkt_in $gp_mkt_verdict {
    volatile;
    "~^1\|-query_string\|(?:GET|HEAD)\|(?<gpmkt_q>[^#]*+)#\k<gpmkt_q>$"  $gp_mkt_allmkt;
    default  "";
}

# New $skip_cache / $skip_reason: changed only when un-skipped.
map $gp_mkt_unskip $gp_mkt_skip_cache {
    volatile;
    "1"      "0";
    default  $gp_mkt_sc;
}
map $gp_mkt_unskip $gp_mkt_skip_reason {
    volatile;
    "1"      "";
    default  $gp_mkt_sr;
}
# Cache key URI: clean path (== stock key of the clean URL) or stock $request_uri.
map $gp_mkt_unskip $gp_mkt_key_uri {
    volatile;
    "1"      $gp_mkt_path;
    default  $request_uri;
}
# $args for PHP (QUERY_STRING): empty when un-skipped, untouched otherwise.
map $gp_mkt_unskip $gp_mkt_args {
    volatile;
    "1"      "";
    default  $args;
}
# Extra REQUEST_URI for PHP only when un-skipped (if_not_empty -> otherwise not sent).
map $gp_mkt_unskip $gp_mkt_request_uri {
    volatile;
    "1"      $gp_mkt_path;
    default  "";
}
# Informational response header.
map $gp_mkt_unskip $gp_mkt_header {
    volatile;
    "1"      "ignored";
    default  "";
}

# PHP never saw the marketing params, so put them back on same-site 3xx
# redirects (trailing slash, www->apex, canonical, 404 guess...). Other hosts
# (S3 signed URLs, payment gateways...) and "//host", "/\host", "/<TAB>/host"
# targets are left untouched.
map $host $gp_mkt_bare_host {
    "~^www\.(?<gpmkt_bh>.+)$"  $gpmkt_bh;
    default                    $host;
}
# $sent_http_location = the Location being sent: PHP's (upstream) or one created
# by nginx itself (e.g. `return 301` in a php-context include).
map "$gp_mkt_unskip|$gp_mkt_bare_host|$sent_http_location" $gp_mkt_location {
    volatile;
    # no query in Location yet
    "~*^1\|(?<gpmkt_h>[^|]*)\|(?<gpmkt_l>(?:https?://(?:www\.)?\k<gpmkt_h>(?::[0-9]+)?(?=[/#]|$)|/(?![/\x5c\t]))[^?#]*)(?<gpmkt_f>#.*)?$"  "$gpmkt_l?$gp_mkt_qs$gpmkt_f";
    # Location already has a query
    "~*^1\|(?<gpmkt_h>[^|]*)\|(?<gpmkt_l>(?:https?://(?:www\.)?\k<gpmkt_h>(?::[0-9]+)?(?=[/?#]|$)|/(?![/\x5c\t]))[^#]*)(?<gpmkt_f>#.*)?$"   "$gpmkt_l&$gp_mkt_qs$gpmkt_f";
    default  $sent_http_location;
}
'''


def fill(tpl, **kw):
    for k, v in kw.items():
        tpl = tpl.replace("@" + k + "@", str(v))
    return tpl


parts = [fill(HEADER, MAX=MAX, MAX_LEN=MAX_LEN, MAX_PATH=MAX_PATH, DIR=DIR)]
for i in range(1, MAX + 1):
    prev = "gp_mkt_q0" if i == 1 else "gp_mkt_r%d" % (i - 1)
    parts.append(fill(STEP, I=i, R_PREV=prev, NEXT=i + 1, DIR=DIR))
parts.append(fill(FOOTER, MAX=MAX, MAX1=MAX + 1))
sys.stdout.write("\n".join(parts))
